# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-Oo_RhoEM968-PWwdTvsT0naa98jvRD
"""

def load_and_chunk_document(file_path, chunk_size=300, overlap=50):
    """
    Reads a text document, splits it into chunks,
    and returns a list of text chunks.

    Parameters:
        file_path (str): Path of the text file.
        chunk_size (int): Maximum number of characters in one chunk.
        overlap (int): Number of overlapping characters.

    Returns:
        list: List of text chunks.
    """

    # Step 1: Check whether the file exists
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"{file_path} does not exist.")

    # Step 2: Open the text file
    with open(file_path, "r", encoding="utf-8") as file:
        document = file.read()

    # Step 3: Create a text splitter
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=overlap,
        separators=["\n\n", "\n", ".", " ", ""]
    )

    # Step 4: Split the document
    chunks = splitter.split_text(document)

    # Step 5: Remove empty chunks
    chunks = [chunk.strip() for chunk in chunks if chunk.strip()]

    # Step 6: Return the chunks
    return chunks

from sentence_transformers import SentenceTransformer

def create_embeddings(chunks, model_name="all-MiniLM-L6-v2"):
    """
    Creates embeddings for all text chunks.
    """

    # Load Sentence Transformer model
    model = SentenceTransformer(model_name)

    # Generate embeddings
    embeddings = model.encode(chunks)

    # Convert NumPy array to Python list
    embeddings = embeddings.tolist()

    return embeddings

embeddings = create_embeddings(chunks)

def search_chunks(query, chunks, embeddings, k=3):
    """
    Searches for the top-k most similar chunks.
    """

    # Load the same embedding model
    model = SentenceTransformer("all-MiniLM-L6-v2")

    # Create embedding for the query
    query_embedding = model.encode([query])

    # Calculate cosine similarity
    similarity_scores = cosine_similarity(query_embedding, embeddings)[0]

    # Get indices of top-k chunks
    top_indices = np.argsort(similarity_scores)[::-1][:k]

    # Store top chunks
    top_chunks = []

    for index in top_indices:
        top_chunks.append(chunks[index])

    return top_chunks

import cohere

def generate_answer(query, context, api_key):
    """
    Generate an answer using Cohere based on the retrieved context.

    Parameters:
        query (str): User question
        context (str): Retrieved document chunks
        api_key (str): Cohere API key

    Returns:
        str: Generated answer
    """

    # Initialize Cohere client
    co = cohere.Client(api_key)

    # Create prompt
    prompt = f"""
You are a helpful AI assistant.

Answer the user's question ONLY using the information provided below.

Context:
{context}

Question:
{query}

Answer:
"""

    # Generate response
    response = co.chat(
        model="command-a-03-2025",
        message=prompt
    )

    return response.text